name: excute-github-actions
run-name: ${{ github.actor }} is excute GitHub Actions
on: [push]
jobs:
  example-job:
    steps:
      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432