name: 执行脚本
run-name: ${{ github.actor }} 正在执行脚本
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: 存储库签出到运行器
        uses: actions/checkout@v4
      - name: 执行js脚本
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432